import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PageTransition from "../components/PageTransition";
import Footer from "@/components/Footer";
import Chatbot from "@/components/Chatbot";
import { get } from "https";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-amber-50 text-black">

        {/* HEADER (UNCHANGED) */}
        <header
  className=" sticky top-0 z-50 flex items-center justify-between px-10 py-3 rounded-b-md bg-white/30 backdrop-blur-xl border-b border-white/10 shadow-md text-black text-xl ">
          <img src="/LOGO.png" alt="SoftLabs Infotech" className="h-12 w-35" />

          <nav className="hidden gap-8 text-sm md:flex">
            <a href="/" className="font-bold hover:text-indigo-600">Home</a>
            <a href="/about" className="font-bold hover:text-indigo-600">About</a>
            <a href="/services" className="font-bold hover:text-indigo-600">Services</a>
            <a href="/value-proposition" className="font-bold hover:text-indigo-600">Value Proposition</a>
            <a href="/lets-grow-together" className="font-bold hover:text-indigo-600">Let’s Grow Together</a>
          </nav>

          <a
            href="/contact"
            className="rounded-lg bg-violet-700 px-5 py-2 text-sm text-white hover:bg-violet-900"
          >
            Contact Us
          </a>
        </header>

        {/* ✅ PAGE TRANSITION CLIENT WRAPPER */}
        <PageTransition>
          {children}
        </PageTransition>
{/* AI Chatbot */}
<Script id="chatbase-init" strategy="afterInteractive">
  {`(function(){if(!window.chatbase||window.chatbase("getState")!=="initialized"){window.chatbase=(...arguments)=>{if(!window.chatbase.q){window.chatbase.q=[]}window.chatbase.q.push(arguments)};window.chatbase=new Proxy(window.chatbase,{get(target,prop){if(prop==="q"){return target.q}return(...args)=>target(prop,...args)}})}const onLoad=function(){const script=document.createElement("script");script.src="https://www.chatbase.co/embed.min.js";script.id="ZG8AMXHUfsUHwh3GBae0-";script.domain="www.chatbase.co";document.body.appendChild(script)};if(document.readyState==="complete"){onLoad()}else{window.addEventListener("load",onLoad)}})();`}
</Script>

      <Footer />
      </body>
    </html>
  );
}
